version: '3'
services:
  docker-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university_base
    ports:
      - '3307:3306'
    volumes:
        - ./data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      timeout: 20s
      retries: 10